#!/usr/bin/env python3

import argparse
from dataclasses import dataclass
from email import policy
from email.parser import HeaderParser
import email.utils
from typing import Iterable, Optional


def parse_rfc2822_date_to_iso(date_header_value: str) -> str:
    dt = email.utils.parsedate_to_datetime(date_header_value.strip())
    if dt is None:
        raise ValueError(f"unable to parse Date header: {date_header_value!r}")
    if dt.tzinfo is not None:
        dt = dt.astimezone().replace(tzinfo=None)
    return dt.date().isoformat()


@dataclass(frozen=True)
class PatchRecord:
    date_iso: str
    subject: str
    payload: str

    def to_text(self) -> str:
        subject = self.subject.strip()
        payload = self.payload.lstrip("\n").rstrip()
        if subject and payload:
            content = f"{subject}\n{payload}"
        elif subject:
            content = subject
        else:
            content = payload
        content = content.rstrip()
        return f"{self.date_iso}\n{content}\n\n"


def extract_record_from_patch_lines(lines: Iterable[str]) -> PatchRecord:
    raw_headers: list[str] = []
    in_headers = False
    in_payload = False
    payload_lines: list[str] = []

    for line in lines:
        if line.startswith("From ") and " 2001" in line:
            in_headers = True
            in_payload = False
            raw_headers = []
            payload_lines = []
            continue

        if not in_headers and not in_payload:
            continue

        if in_headers:
            raw_headers.append(line)
            if line == "\n":
                in_headers = False
                in_payload = True
            continue

        if in_payload:
            payload_lines.append(line)

    parser = HeaderParser(policy=policy.default)
    headers = parser.parsestr("".join(raw_headers))

    date_raw = headers.get("Date") or ""
    subject = headers.get("Subject") or ""
    date_iso = "1970-01-01"
    if date_raw.strip():
        date_iso = parse_rfc2822_date_to_iso(date_raw)

    payload = "".join(payload_lines)
    return PatchRecord(date_iso=date_iso, subject=str(subject), payload=payload)


def extract_record_from_patch_file(path: str) -> PatchRecord:
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return extract_record_from_patch_lines(f)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Filter a git format-patch file into Date + message body text.")
    parser.add_argument("-i", "--input", required=True, help="Path to a .patch file generated by git format-patch.")
    parser.add_argument("-o", "--output", help="Path to output txt (default: stdout).")
    args = parser.parse_args(argv)

    record = extract_record_from_patch_file(args.input).to_text()
    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(record)
        return 0

    print(record, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(__import__("sys").argv[1:]))
